Add initial implementation of Update command
AY2425S1-CS2103T-T09-1/tp pull request #111
Opened 2024-10-23 11:00 UTC by blanklogic

Resolves #92

2024-10-23 14:50 UTC, Shux347 approved these changes

2024-10-23 14:50 UTC, Shux347 commented on src/test/java/seedu/internbuddy/logic/commands/UpdateCommandTest.java
Tests are well-written and thorough. Thanks for keeping quality in mind.

2024-10-23 14:50 UTC, Shux347 commented on src/main/java/seedu/internbuddy/logic/commands/WithdrawCommand.java
> +        requireNonNull(companyIndex);
This is a solid improvement. Thanks for making it easier to maintain.

2024-10-23 16:39 UTC, uniqly requested changes
Overall solid work! But the testing could be more complete (not to say that it is not thorough). 😃

2024-10-23 16:39 UTC, uniqly commented on src/main/java/seedu/internbuddy/logic/commands/UpdateCommand.java
> +            + "Example: " + COMMAND_WORD + " 1 1 "
Not sure if we want to make the indexes to have prefixes like in the `WithdrawCommand` in #108 to be consistent.

2024-10-23 16:39 UTC, uniqly commented on src/test/java/seedu/internbuddy/logic/commands/UpdateCommandTest.java
> +    }
Good test cases, but I think the `equals_sameObject_returnsTrue` is not exactly testing equality for the same object but rather the another `UpdateCommandTest` instance with the same values; we should test for both. 

Would including a testing for different individual parameters be more concrete in `equals_differentObject_returnsFalse`? 

Perhaps unifying the `equals` test into one test with the 3 different cases could be better?

2024-10-24 12:22 UTC, uniqly commented on docs/UserGuide.md
> +| **Update**   | `update c/COMPANY_INDEX app/APPLICATION_INDEX as/APPLICATION_STATUS`<br> e.g.,`update 1 1 as/OA`                                                                                  |
Minor typo. Should be `update c/1 app/1 as/OA` instead.

2024-10-24 12:38 UTC, uniqly approved these changes
LGTM! 👍

2024-10-24 13:02 UTC, merged