UserGuide format tweaks
AY2425S1-CS2103T-T09-1/tp pull request #317
Opened 2024-11-10 17:08 UTC by realqijun

# Resolves
* #298 (Sorry Simon),
* #315

2024-11-10 18:10 UTC, blanklogic requested changes
Great addition of pictures, some nits regarding where `reopen` should be placed. 

Also regarding the organisation of User Guide I have some questions regarding #298 . Should we make the segregation more obvious with header tags for Company commands, Application commands and General commands for the entire User Guide?

2024-11-10 18:10 UTC, blanklogic commented on docs/UserGuide.md
> +| **Reopen**   | `reopen INDEX`                                                                                                                                                                   |
Think according to #298 of reorganising commands to "Company", "Application", "Misc.", Reopen belongs under Company instead.

2024-11-11 01:54 UTC, uniqly commented
@blanklogic @realqijun Regarding the organisation with header, I think that is good. I've seen other groups do that also.

2024-11-11 04:50 UTC, blanklogic approved these changes
Thanks for making the requested changes. LGTM!

2024-11-11 05:25 UTC, uniqly approved these changes
LGTM!

2024-11-11 05:26 UTC, merged