Edits to UG and DG
AY2425S1-CS2103T-T09-1/tp pull request #319
Opened 2024-11-10 17:34 UTC by meerkatboy

Addresses the issues:
#308 - added tip on adding tags to company
#268 - added to Known Issues. Will add to Planned Enhancements in DG
#258 - created the relevant user stories
#251 - edited the caption to "update" application

Also made some minor edits with regards to punctuation and alphabet casing, after initial skimming through,

note: ignore the branch name, edited both DG and UG

2024-11-10 17:54 UTC, uniqly requested changes
Some edits to make, but looks good. @meerkatboy Will the adding of the planned enhancement be in a different PR #297 or will it be in this one

2024-11-10 17:54 UTC, uniqly commented on docs/DeveloperGuide.md
> +| `* * *`  | STEM major planning to apply for internships                | find specific companies based on application names or details | retrieve information about companies without having to go th
This should be 2 stars

2024-11-10 17:54 UTC, uniqly commented on docs/DeveloperGuide.md
> +| `* * *`  | STEM major planning to apply for internships                | unfavourite a company                                         | unmark that company as a priority if no longer relevant
This should be 2 stars as well

2024-11-10 17:54 UTC, uniqly commented on docs/DeveloperGuide.md
> +| `* * *`  |                                                             |                                                               |
Why is there an empty row?

2024-11-10 17:54 UTC, uniqly commented on docs/DeveloperGuide.md
>  *{More to be added}*
Can remove this.

2024-11-10 17:54 UTC, uniqly commented on docs/UserGuide.md
> +**Tip 2:** Tags can be a useful way to categorise different companies into various groups!
```suggestion
**Tip 2:** Tags can be a useful way to categorise different companies into various groups! <br>
```

2024-11-11 04:51 UTC, blanklogic approved these changes
LGTM!

2024-11-11 06:08 UTC, uniqly approved these changes
LGTM!

2024-11-11 06:08 UTC, merged