Edited edit and find commands
AY2425S1-CS2103T-T09-1/tp pull request #59
Opened 2024-10-15 09:27 UTC by meerkatboy

Changes to ensure application works with companies instead of persons

2024-10-16 13:24 UTC, blanklogic requested changes
Please remove PersonListPanel.java from the PR and properly sync your fork as it seems like your fork repo has not been synced to upstream.

2024-10-17 02:31 UTC, uniqly requested changes
I think `EditCompanyDescriptor` should include applications as it will be used for the `apply` and `withdraw` applications commands

2024-10-17 02:31 UTC, uniqly commented on src/main/java/seedu/internbuddy/logic/commands/Command.java
> +     * @param model {@code ModelCompany} which the command should operate on.
Should be `Model` instead of `ModelCompany`

2024-10-17 02:31 UTC, uniqly commented on src/test/java/seedu/internbuddy/logic/commands/CommandTestUtil.java
>      static {
This shouldn't be here as it is no longer used.

2024-10-17 03:08 UTC, closed without merging

2024-10-17 03:08 UTC, meerkatboy commented
Closed, see #69